stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: 'ubuntu-latest'
    steps:
    - script: echo "Building the application"

- stage: Test
  jobs:
  - job: TestJob
    pool:
      name: 'ubuntu-latest'
    dependsOn: Build
    steps:
    - script: echo "Running tests"

- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      name: 'ubuntu-latest'
    dependsOn: Test
    steps:
    - script: echo "Deploying the application"
